"""
Central menu router for Andishkadeh Management & Market.

Connected modules:
- Main Menu
- Management
- Management Quiz
- International Trade
- Psychology & Social Work
- Marketing & Sales
- Economy & Market

This router is intentionally compatible with the callback_data
generated by each module's handlers.

The router keeps module-specific business logic inside each
module's handlers/service layer.
"""

from __future__ import annotations

import logging

from telegram import Update
from telegram.ext import ContextTypes

from core.keyboards import main_menu_keyboard


# ==========================================================
# Management
# ==========================================================

from modules.management.handlers import (
    show_management_menu,
    show_management_chapter,
    show_management_lesson,
    start_management_quiz,
    answer_management_quiz,
    next_management_quiz_question,
    stop_management_quiz,
    cancel_management_quiz,
)


# ==========================================================
# International Trade
# ==========================================================

from modules.international_trade.handlers import (
    show_international_trade_menu,
    show_international_trade_chapters,
    show_international_trade_chapter,
    show_international_trade_lesson,
    complete_international_trade_lesson,
    start_international_trade_quiz,
    answer_international_trade_quiz,
    cancel_international_trade_quiz,
)


# ==========================================================
# Psychology & Social Work
# ==========================================================

from modules.psychology.handlers import (
    show_psychology_menu,
    show_psychology_chapter,
    show_psychology_lesson,
    complete_psychology_lesson,
    start_psychology_quiz,
    answer_psychology_quiz,
    cancel_psychology_quiz,
)


# ==========================================================
# Marketing & Sales
# ==========================================================

from modules.marketing.handlers import (
    show_marketing_menu,
    show_marketing_chapter,
    show_marketing_lesson,
    start_marketing_quiz,
    start_marketing_chapter_quiz,
    answer_marketing_quiz,
    finish_marketing_quiz,
    show_marketing_statistics,
)


# ==========================================================
# Economy & Market
# ==========================================================

from modules.economy.handlers import (
    show_economy_menu,
    show_economy_chapter,
    show_economy_lesson,
    start_economy_quiz,
    start_economy_chapter_quiz,
    answer_economy_quiz,
    finish_economy_quiz,
    show_economy_statistics,
)


logger = logging.getLogger(__name__)


# ==========================================================
# Main Menu Text
# ==========================================================

MAIN_MENU_TEXT = (
    "🏛️ <b>اندیشکده مدیریت و بازار</b>\n\n"
    "مرکز تخصصی آموزش مدیریت، بازرگانی، اقتصاد، "
    "بازاریابی و مهارت‌های حرفه‌ای.\n\n"
    "لطفاً بخش موردنظر خود را انتخاب کنید:"
)


# ==========================================================
# Main Menu
# ==========================================================

async def show_main_menu(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:
    """Show the main bot menu."""

    query = update.callback_query

    if query is not None:
        try:
            await query.answer()
        except Exception:
            logger.exception(
                "Failed to answer main menu callback."
            )

        try:
            await query.edit_message_text(
                text=MAIN_MENU_TEXT,
                reply_markup=main_menu_keyboard(),
                parse_mode="HTML",
            )
            return

        except Exception:
            logger.exception(
                "Failed to edit main menu message."
            )

    message = update.effective_message

    if message is not None:
        await message.reply_text(
            text=MAIN_MENU_TEXT,
            reply_markup=main_menu_keyboard(),
            parse_mode="HTML",
        )


# ==========================================================
# Central Callback Router
# ==========================================================

async def route_menu_callback(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
) -> None:
    """
    Central callback router.

    Handles callbacks that are not intercepted by dedicated
    module handlers.
    """

    query = update.callback_query

    if query is None:
        return

    data = query.data or ""

    logger.info(
        "Central menu callback received: %s",
        data,
    )


    # ======================================================
    # Main Menu
    # ======================================================

    if data == "menu_main":

        await show_main_menu(
            update,
            context,
        )

        return


    # ======================================================
    # Management
    # ======================================================

    if data == "menu_management":

        await show_management_menu(
            update,
            context,
        )

        return


    if data.startswith(
        "management_chapter:"
    ):

        await show_management_chapter(
            update,
            context,
        )

        return


    if data.startswith(
        "management_lesson:"
    ):

        await show_management_lesson(
            update,
            context,
        )

        return


    if data == "management_quiz_start":

        await start_management_quiz(
            update,
            context,
        )

        return


    if data.startswith(
        "management_quiz_answer:"
    ):

        await answer_management_quiz(
            update,
            context,
        )

        return


    if data == "management_quiz_next":

        await next_management_quiz_question(
            update,
            context,
        )

        return


    if data == "management_quiz_stop":

        await stop_management_quiz(
            update,
            context,
        )

        return


    if data == "management_quiz_cancel":

        await cancel_management_quiz(
            update,
            context,
        )

        return


    # ======================================================
    # International Trade
    # ======================================================

    if data in {
        "menu_international_trade",
        "menu_trade",
    }:

        await show_international_trade_menu(
            update,
            context,
        )

        return


    if data == "trade_chapters":

        await show_international_trade_chapters(
            update,
            context,
        )

        return


    if data.startswith(
        "trade_chapter:"
    ):

        await show_international_trade_chapter(
            update,
            context,
        )

        return


    if data.startswith(
        "trade_lesson:"
    ):

        await show_international_trade_lesson(
            update,
            context,
        )

        return


    if data.startswith(
        "trade_complete:"
    ):

        await complete_international_trade_lesson(
            update,
            context,
        )

        return


    if data.startswith(
        "trade_quiz:"
    ):

        await start_international_trade_quiz(
            update,
            context,
        )

        return


    if data.startswith(
        "trade_quiz_answer:"
    ):

        await answer_international_trade_quiz(
            update,
            context,
        )

        return


    if data.startswith(
        "trade_quiz_cancel:"
    ):

        await cancel_international_trade_quiz(
            update,
            context,
        )

        return


    # ======================================================
    # Psychology & Social Work
    # ======================================================

    if data == "menu_psychology":

        await show_psychology_menu(
            update,
            context,
        )

        return


    if data.startswith(
        "psychology_chapter:"
    ):

        await show_psychology_chapter(
            update,
            context,
        )

        return


    if data.startswith(
        "psychology_lesson:"
    ):

        await show_psychology_lesson(
            update,
            context,
        )

        return


    if data.startswith(
        "psychology_complete:"
    ):

        await complete_psychology_lesson(
            update,
            context,
        )

        return


    if data.startswith(
        "psychology_quiz:"
    ):

        await start_psychology_quiz(
            update,
            context,
        )

        return


    if data.startswith(
        "psychology_quiz_answer:"
    ):

        await answer_psychology_quiz(
            update,
            context,
        )

        return


    if data == "psychology_quiz_cancel":

        await cancel_psychology_quiz(
            update,
            context,
        )

        return


    # ======================================================
    # Marketing & Sales
    # ======================================================

    if data in {
        "menu_marketing",
        "menu_marketing_sales",
    }:

        await show_marketing_menu(
            update,
            context,
        )

        return


    # ------------------------------------------------------
    # Marketing Chapter
    # ------------------------------------------------------

    if data.startswith(
        "marketing_chapter:"
    ):

        await show_marketing_chapter(
            update,
            context,
        )

        return


    # ------------------------------------------------------
    # Marketing Lesson
    # ------------------------------------------------------

    if data.startswith(
        "marketing_lesson:"
    ):

        await show_marketing_lesson(
            update,
            context,
        )

        return


    # ------------------------------------------------------
    # Marketing Lesson Quiz
    # ------------------------------------------------------

    if data.startswith(
        "marketing_quiz_lesson:"
    ):

        await start_marketing_quiz(
            update,
            context,
        )

        return


    # ------------------------------------------------------
    # Marketing Chapter Quiz
    # ------------------------------------------------------

    if data.startswith(
        "marketing_quiz_chapter:"
    ):

        await start_marketing_chapter_quiz(
            update,
            context,
        )

        return


    # ------------------------------------------------------
    # Marketing Complete Quiz
    # ------------------------------------------------------

    if data == "marketing_quiz_all":

        await start_marketing_quiz(
            update,
            context,
        )

        return


    # ------------------------------------------------------
    # Marketing Quiz Answer
    # ------------------------------------------------------

    if data.startswith(
        "marketing_quiz_answer:"
    ):

        await answer_marketing_quiz(
            update,
            context,
        )

        return


    # ------------------------------------------------------
    # Marketing Quiz Finish
    # ------------------------------------------------------

    if data == "marketing_quiz_finish":

        await finish_marketing_quiz(
            update,
            context,
        )

        return


    # ------------------------------------------------------
    # Marketing Statistics
    # ------------------------------------------------------

    if data == "marketing_statistics":

        await show_marketing_statistics(
            update,
            context,
        )

        return


    # ======================================================
    # Economy & Market
    # ======================================================

    if data in {
        "menu_economy",
        "menu_economy_market",
    }:

        await show_economy_menu(
            update,
            context,
        )

        return


    # ------------------------------------------------------
    # Economy Chapters
    # ------------------------------------------------------

    if data in {
        "economy_chapters",
        "economy_chapter_list",
    }:

        await show_economy_menu(
            update,
            context,
        )

        return


    # ------------------------------------------------------
    # Economy Chapter
    # ------------------------------------------------------

    if data.startswith(
        "economy_chapter:"
    ):

        await show_economy_chapter(
            update,
            context,
        )

        return


    # ------------------------------------------------------
    # Economy Lesson
    # ------------------------------------------------------

    if data.startswith(
        "economy_lesson:"
    ):

        await show_economy_lesson(
            update,
            context,
        )

        return


    # ------------------------------------------------------
    # Economy Quiz All
    # ------------------------------------------------------

    if data in {
        "economy_quiz_all",
        "economy_quiz_start",
    }:

        await start_economy_quiz(
            update,
            context,
        )

        return


    # ------------------------------------------------------
    # Economy Chapter Quiz
    # ------------------------------------------------------

    if data.startswith(
        "economy_quiz_chapter:"
    ):

        await start_economy_chapter_quiz(
            update,
            context,
        )

        return


    # ------------------------------------------------------
    # Economy Lesson Quiz
    # ------------------------------------------------------

    if data.startswith(
        "economy_quiz_lesson:"
    ):

        await start_economy_quiz(
            update,
            context,
        )

        return


    # ------------------------------------------------------
    # Economy Quiz Answer
    # ------------------------------------------------------

    if data.startswith(
        "economy_quiz_answer:"
    ):

        await answer_economy_quiz(
            update,
            context,
        )

        return


    # ------------------------------------------------------
    # Economy Quiz Finish
    # ------------------------------------------------------

    if data == "economy_quiz_finish":

        await finish_economy_quiz(
            update,
            context,
        )

        return


    # ------------------------------------------------------
    # Economy Statistics
    # ------------------------------------------------------

    if data == "economy_statistics":

        await show_economy_statistics(
            update,
            context,
        )

        return


    # ======================================================
    # Unknown Callback
    # ======================================================

    logger.warning(
        "Unknown callback received: %s",
        data,
    )

    try:

        await query.answer(
            "این بخش هنوز فعال نشده است.",
            show_alert=False,
        )

    except Exception:

        logger.exception(
            "Failed to answer unknown callback: %s",
            data,
        )


# ==========================================================
# Health Check
# ==========================================================

def menu_health_check() -> bool:
    """
    Basic central menu health check.

    Ensures all required module handler functions
    are available and callable.
    """

    try:

        required_functions = (

            # Core
            main_menu_keyboard,
            show_main_menu,
            route_menu_callback,

            # Management
            show_management_menu,
            show_management_chapter,
            show_management_lesson,
            start_management_quiz,
            answer_management_quiz,
            next_management_quiz_question,
            stop_management_quiz,
            cancel_management_quiz,

            # International Trade
            show_international_trade_menu,
            show_international_trade_chapters,
            show_international_trade_chapter,
            show_international_trade_lesson,
            complete_international_trade_lesson,
            start_international_trade_quiz,
            answer_international_trade_quiz,
            cancel_international_trade_quiz,

            # Psychology
            show_psychology_menu,
            show_psychology_chapter,
            show_psychology_lesson,
            complete_psychology_lesson,
            start_psychology_quiz,
            answer_psychology_quiz,
            cancel_psychology_quiz,

            # Marketing
            show_marketing_menu,
            show_marketing_chapter,
            show_marketing_lesson,
            start_marketing_quiz,
            start_marketing_chapter_quiz,
            answer_marketing_quiz,
            finish_marketing_quiz,
            show_marketing_statistics,

            # Economy
            show_economy_menu,
            show_economy_chapter,
            show_economy_lesson,
            start_economy_quiz,
            start_economy_chapter_quiz,
            answer_economy_quiz,
            finish_economy_quiz,
            show_economy_statistics,
        )

        return all(
            callable(function)
            for function in required_functions
        )

    except Exception:

        logger.exception(
            "Central menu health check failed."
        )

        return False


# ==========================================================
# Public Exports
# ==========================================================

__all__ = [
    "MAIN_MENU_TEXT",
    "show_main_menu",
    "route_menu_callback",
    "menu_health_check",
]
